### ISSUE TITLE
 Running setup.py install for projectq ... error

### ISSUE THREAD

**Issue by Chunde** [quantumlib/OpenFermion-ProjectQ#37]
Hi, I tried to install this in ubuntu subsystem of windows 10, but failed, here is the output message, any idea?
```Requirement already satisfied: bleach in /usr/local/lib/python3.4/dist-packages (from nbconvert->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.4/dist-packages (from nbconvert->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.4/dist-packages (from jupyter-client->jupyter-console->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Requirement already satisfied: jedi>=0.10 in /usr/local/lib/python3.4/dist-packages (from ipython->jupyter-console->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.4/dist-packages (from ipython->jupyter-console->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.4/dist-packages (from ipython->jupyter-console->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Requirement already satisfied: typing; python_version <= "3.4" in /usr/local/lib/python3.4/dist-packages (from ipython->jupyter-console->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.4/dist-packages (from ipython->jupyter-console->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.4/dist-packages (from prompt-toolkit<2.0.0,>=1.0.0->jupyter-console->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Requirement already satisfied: backports_abc>=0.4 in /usr/local/lib/python3.4/dist-packages (from tornado>=4.0->ipykernel->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.4/dist-packages (from nbformat->notebook->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.4/dist-packages (from terminado>=0.3.3; sys_platform != "win32"->notebook->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.4/dist-packages (from jinja2->notebook->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Requirement already satisfied: html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre in /usr/local/lib/python3.4/dist-packages (from bleach->nbconvert->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Requirement already satisfied: parso==0.1.0 in /usr/local/lib/python3.4/dist-packages (from jedi>=0.10->ipython->jupyter-console->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Requirement already satisfied: webencodings in /usr/local/lib/python3.4/dist-packages (from html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre->bleach->nbconvert->jupyter->openfermion>=0.1->openfermionprojectq==0.1)
Installing collected packages: projectq, openfermionprojectq
  Running setup.py install for projectq ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-i4sb6p9d/projectq/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-acsfe88l-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.4
    creating build/lib.linux-x86_64-3.4/projectq
    copying projectq/__init__.py -> build/lib.linux-x86_64-3.4/projectq
    copying projectq/_version.py -> build/lib.linux-x86_64-3.4/projectq
    creating build/lib.linux-x86_64-3.4/projectq/backends
    copying projectq/backends/__init__.py -> build/lib.linux-x86_64-3.4/projectq/backends
    copying projectq/backends/_printer.py -> build/lib.linux-x86_64-3.4/projectq/backends
    copying projectq/backends/_printer_test.py -> build/lib.linux-x86_64-3.4/projectq/backends
    copying projectq/backends/_resource.py -> build/lib.linux-x86_64-3.4/projectq/backends
    copying projectq/backends/_resource_test.py -> build/lib.linux-x86_64-3.4/projectq/backends
    creating build/lib.linux-x86_64-3.4/projectq/cengines
    copying projectq/cengines/__init__.py -> build/lib.linux-x86_64-3.4/projectq/cengines
    copying projectq/cengines/_basics.py -> build/lib.linux-x86_64-3.4/projectq/cengines
    copying projectq/cengines/_basics_test.py -> build/lib.linux-x86_64-3.4/projectq/cengines
    copying projectq/cengines/_cmdmodifier.py -> build/lib.linux-x86_64-3.4/projectq/cengines
    copying projectq/cengines/_cmdmodifier_test.py -> build/lib.linux-x86_64-3.4/projectq/cengines
    copying projectq/cengines/_ibmcnotmapper.py -> build/lib.linux-x86_64-3.4/projectq/cengines
    copying projectq/cengines/_ibmcnotmapper_test.py -> build/lib.linux-x86_64-3.4/projectq/cengines
    copying projectq/cengines/_main.py -> build/lib.linux-x86_64-3.4/projectq/cengines
    copying projectq/cengines/_main_test.py -> build/lib.linux-x86_64-3.4/projectq/cengines
    copying projectq/cengines/_optimize.py -> build/lib.linux-x86_64-3.4/projectq/cengines
    copying projectq/cengines/_optimize_test.py -> build/lib.linux-x86_64-3.4/projectq/cengines
    copying projectq/cengines/_tagremover.py -> build/lib.linux-x86_64-3.4/projectq/cengines
    copying projectq/cengines/_tagremover_test.py -> build/lib.linux-x86_64-3.4/projectq/cengines
    copying projectq/cengines/_testengine.py -> build/lib.linux-x86_64-3.4/projectq/cengines
    copying projectq/cengines/_testengine_test.py -> build/lib.linux-x86_64-3.4/projectq/cengines
    creating build/lib.linux-x86_64-3.4/projectq/libs
    copying projectq/libs/__init__.py -> build/lib.linux-x86_64-3.4/projectq/libs
    creating build/lib.linux-x86_64-3.4/projectq/meta
    copying projectq/meta/__init__.py -> build/lib.linux-x86_64-3.4/projectq/meta
    copying projectq/meta/_compute.py -> build/lib.linux-x86_64-3.4/projectq/meta
    copying projectq/meta/_compute_test.py -> build/lib.linux-x86_64-3.4/projectq/meta
    copying projectq/meta/_control.py -> build/lib.linux-x86_64-3.4/projectq/meta
    copying projectq/meta/_control_test.py -> build/lib.linux-x86_64-3.4/projectq/meta
    copying projectq/meta/_dagger.py -> build/lib.linux-x86_64-3.4/projectq/meta
    copying projectq/meta/_dagger_test.py -> build/lib.linux-x86_64-3.4/projectq/meta
    copying projectq/meta/_dirtyqubit.py -> build/lib.linux-x86_64-3.4/projectq/meta
    copying projectq/meta/_dirtyqubit_test.py -> build/lib.linux-x86_64-3.4/projectq/meta
    copying projectq/meta/_loop.py -> build/lib.linux-x86_64-3.4/projectq/meta
    copying projectq/meta/_loop_test.py -> build/lib.linux-x86_64-3.4/projectq/meta
    copying projectq/meta/_qubitplacement.py -> build/lib.linux-x86_64-3.4/projectq/meta
    copying projectq/meta/_qubitplacement_test.py -> build/lib.linux-x86_64-3.4/projectq/meta
    copying projectq/meta/_util.py -> build/lib.linux-x86_64-3.4/projectq/meta
    copying projectq/meta/_util_test.py -> build/lib.linux-x86_64-3.4/projectq/meta
    creating build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/__init__.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_basics.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_basics_test.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_command.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_command_test.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_gates.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_gates_test.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_metagates.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_metagates_test.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_qftgate.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_qftgate_test.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_qubit_operator.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_qubit_operator_test.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_shortcuts.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_shortcuts_test.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_time_evolution.py -> build/lib.linux-x86_64-3.4/projectq/ops
    copying projectq/ops/_time_evolution_test.py -> build/lib.linux-x86_64-3.4/projectq/ops
    creating build/lib.linux-x86_64-3.4/projectq/setups
    copying projectq/setups/__init__.py -> build/lib.linux-x86_64-3.4/projectq/setups
    copying projectq/setups/default.py -> build/lib.linux-x86_64-3.4/projectq/setups
    copying projectq/setups/ibm.py -> build/lib.linux-x86_64-3.4/projectq/setups
    copying projectq/setups/ibm_test.py -> build/lib.linux-x86_64-3.4/projectq/setups
    creating build/lib.linux-x86_64-3.4/projectq/tests
    copying projectq/tests/__init__.py -> build/lib.linux-x86_64-3.4/projectq/tests
    copying projectq/tests/_factoring_test.py -> build/lib.linux-x86_64-3.4/projectq/tests
    creating build/lib.linux-x86_64-3.4/projectq/types
    copying projectq/types/__init__.py -> build/lib.linux-x86_64-3.4/projectq/types
    copying projectq/types/_qubit.py -> build/lib.linux-x86_64-3.4/projectq/types
    copying projectq/types/_qubit_test.py -> build/lib.linux-x86_64-3.4/projectq/types
    creating build/lib.linux-x86_64-3.4/projectq/backends/_circuits
    copying projectq/backends/_circuits/__init__.py -> build/lib.linux-x86_64-3.4/projectq/backends/_circuits
    copying projectq/backends/_circuits/_drawer.py -> build/lib.linux-x86_64-3.4/projectq/backends/_circuits
    copying projectq/backends/_circuits/_drawer_test.py -> build/lib.linux-x86_64-3.4/projectq/backends/_circuits
    copying projectq/backends/_circuits/_to_latex.py -> build/lib.linux-x86_64-3.4/projectq/backends/_circuits
    copying projectq/backends/_circuits/_to_latex_test.py -> build/lib.linux-x86_64-3.4/projectq/backends/_circuits
    creating build/lib.linux-x86_64-3.4/projectq/backends/_ibm
    copying projectq/backends/_ibm/__init__.py -> build/lib.linux-x86_64-3.4/projectq/backends/_ibm
    copying projectq/backends/_ibm/_ibm.py -> build/lib.linux-x86_64-3.4/projectq/backends/_ibm
    copying projectq/backends/_ibm/_ibm_http_client.py -> build/lib.linux-x86_64-3.4/projectq/backends/_ibm
    copying projectq/backends/_ibm/_ibm_http_client_test.py -> build/lib.linux-x86_64-3.4/projectq/backends/_ibm
    copying projectq/backends/_ibm/_ibm_test.py -> build/lib.linux-x86_64-3.4/projectq/backends/_ibm
    creating build/lib.linux-x86_64-3.4/projectq/backends/_sim
    copying projectq/backends/_sim/__init__.py -> build/lib.linux-x86_64-3.4/projectq/backends/_sim
    copying projectq/backends/_sim/_classical_simulator.py -> build/lib.linux-x86_64-3.4/projectq/backends/_sim
    copying projectq/backends/_sim/_classical_simulator_test.py -> build/lib.linux-x86_64-3.4/projectq/backends/_sim
    copying projectq/backends/_sim/_pysim.py -> build/lib.linux-x86_64-3.4/projectq/backends/_sim
    copying projectq/backends/_sim/_simulator.py -> build/lib.linux-x86_64-3.4/projectq/backends/_sim
    copying projectq/backends/_sim/_simulator_test.py -> build/lib.linux-x86_64-3.4/projectq/backends/_sim
    creating build/lib.linux-x86_64-3.4/projectq/cengines/_replacer
    copying projectq/cengines/_replacer/__init__.py -> build/lib.linux-x86_64-3.4/projectq/cengines/_replacer
    copying projectq/cengines/_replacer/_decomposition_rule.py -> build/lib.linux-x86_64-3.4/projectq/cengines/_replacer
    copying projectq/cengines/_replacer/_decomposition_rule_set.py -> build/lib.linux-x86_64-3.4/projectq/cengines/_replacer
    copying projectq/cengines/_replacer/_decomposition_rule_test.py -> build/lib.linux-x86_64-3.4/projectq/cengines/_replacer
    copying projectq/cengines/_replacer/_replacer.py -> build/lib.linux-x86_64-3.4/projectq/cengines/_replacer
    copying projectq/cengines/_replacer/_replacer_test.py -> build/lib.linux-x86_64-3.4/projectq/cengines/_replacer
    creating build/lib.linux-x86_64-3.4/projectq/libs/math
    copying projectq/libs/math/__init__.py -> build/lib.linux-x86_64-3.4/projectq/libs/math
    copying projectq/libs/math/_constantmath.py -> build/lib.linux-x86_64-3.4/projectq/libs/math
    copying projectq/libs/math/_constantmath_test.py -> build/lib.linux-x86_64-3.4/projectq/libs/math
    copying projectq/libs/math/_default_rules.py -> build/lib.linux-x86_64-3.4/projectq/libs/math
    copying projectq/libs/math/_gates.py -> build/lib.linux-x86_64-3.4/projectq/libs/math
    copying projectq/libs/math/_gates_test.py -> build/lib.linux-x86_64-3.4/projectq/libs/math
    creating build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/__init__.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/_gates_test.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/arb1qubit2rzandry.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/arb1qubit2rzandry_test.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/carb1qubit2cnotrzandry.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/carb1qubit2cnotrzandry_test.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/cnu2toffoliandcu.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/cnu2toffoliandcu_test.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/crz2cxandrz.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/entangle.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/globalphase.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/ph2r.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/qft2crandhadamard.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/r2rzandph.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/swap2cnot.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/time_evolution.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/time_evolution_test.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    copying projectq/setups/decompositions/toffoli2cnotandtgate.py -> build/lib.linux-x86_64-3.4/projectq/setups/decompositions
    running build_ext
    creating tmp
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c /tmp/tmpqoau35tz.cpp -o tmp/tmpqoau35tz.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c /tmp/tmpvsfl3ds8.cpp -o tmp/tmpvsfl3ds8.o -fopenmp
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c /tmp/tmp00xhcqtg.cpp -o tmp/tmp00xhcqtg.o -march=native
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    /tmp/tmp00xhcqtg.cpp: In function ‘int main(int, char**)’:
    /tmp/tmp00xhcqtg.cpp:2:44: warning: unused variable ‘neg’ [-Wunused-variable]
     int main (int argc, char **argv) { __m256d neg = _mm256_set1_pd(1.0); }
                                                ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c /tmp/tmpmhyf3m53.cpp -o tmp/tmpmhyf3m53.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c /tmp/tmpb0fziwko.cpp -o tmp/tmpb0fziwko.o -fvisibility=hidden
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    building 'projectq.backends._sim._cppsim' extension
    creating build/temp.linux-x86_64-3.4
    creating build/temp.linux-x86_64-3.4/projectq
    creating build/temp.linux-x86_64-3.4/projectq/backends
    creating build/temp.linux-x86_64-3.4/projectq/backends/_sim
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/include/python3.4 -I/home/xmuhcd/.local/include/python3.4m -I/usr/include/python3.4m -c projectq/backends/_sim/_cppsim.cpp -o build/temp.linux-x86_64-3.4/projectq/backends/_sim/_cppsim.o -DINTRIN -march=native -fopenmp -DVERSION_INFO="0.3.5" -std=c++11 -fvisibility=hidden
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from /usr/local/include/python3.4/pybind11/pytypes.h:12:0,
                     from /usr/local/include/python3.4/pybind11/cast.h:13,
                     from /usr/local/include/python3.4/pybind11/attr.h:13,
                     from /usr/local/include/python3.4/pybind11/pybind11.h:43,
                     from projectq/backends/_sim/_cppsim.cpp:13:
    /usr/local/include/python3.4/pybind11/detail/common.h:111:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib/python3.4/distutils/unixccompiler.py", line 116, in _compile
        extra_postargs)
      File "/usr/lib/python3.4/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.4/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.4/distutils/spawn.py", line 162, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-build-i4sb6p9d/projectq/setup.py", line 146, in build_extensions
        build_ext.build_extensions(self)
      File "/usr/lib/python3.4/distutils/command/build_ext.py", line 448, in build_extensions
        self.build_extension(ext)
      File "/usr/local/lib/python3.4/dist-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.4/distutils/command/build_ext.py", line 503, in build_extension
        depends=ext.depends)
      File "/usr/lib/python3.4/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.4/distutils/unixccompiler.py", line 118, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-i4sb6p9d/projectq/setup.py", line 171, in <module>
        packages=find_packages()
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.4/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.4/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.4/dist-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/usr/lib/python3.4/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-build-i4sb6p9d/projectq/setup.py", line 148, in build_extensions
        self.warning("")
      File "/tmp/pip-build-i4sb6p9d/projectq/setup.py", line 151, in warning
        raise Exception(warning_text + "\nCould not install the C++-Simulator."
    Exception:
    Could not install the C++-Simulator.
    ProjectQ will default to the (slow) Python simulator.
    Use --without-cppsimulator to skip building the (faster) C++ version of the simulator.

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-i4sb6p9d/projectq/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-acsfe88l-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-i4sb6p9d/projectq/```

**Comment by babbush** [comment]
Thanks for sharing this issue. It appears that the installation problem you are experiencing is a problem with the installation of ProjectQ, rather than a problem with installing our plugin itself. So perhaps this is better to share at https://github.com/ProjectQ-Framework/ProjectQ. I am not actually sure if ProjectQ is intended to be used on Windows. It is possible that to fix this issue you will need to specify the C++ compilers more clearly for the ProjectQ install.

If you continue to have problems I would suggest you install OpenFermion together with all of its plugins using the Docker installation: https://github.com/quantumlib/OpenFermion/tree/master/docker
This method of installing has been tested on Windows and will automatically install all the libraries used in OpenFermion and plugins.

I will close this issue as the problem seems to be primarily a problem with ProjectQ. Thanks!

**Comment by Chunde** [comment]
hi @babbush :

It seems to me that the OpenFermin-ProjectQ depends on ProjectQ, so when I execute the command, it will try to install ProjectQ first.  I found that from the following output:

_Installing collected packages: projectq, openfermionprojectq
Running setup.py install for projectq ... error_

that why it is failed. I do checkout the ProjectQ and try to install, and confirm that you are right, it's the issue with ProjectQ, Thanks very much.
